"use client";

import { FormEvent, useEffect, useState } from "react";
import { AppSidebar } from "../components/app-sidebar";
import styles from "./inventory.module.css";

type Item = { id: string; code: string; name: string; manufacturer: string | null; model: string | null; unit: string; clientRatePaise: number; category: { name: string } };
type Form = { category: string; item: string; brand: string; model: string; unitPrice: string; unit: string };
const empty: Form = { category: "", item: "", brand: "", model: "", unitPrice: "", unit: "Per Day" };
const price = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

export function InventoryManager() {
  const [items, setItems] = useState<Item[]>([]); const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<Item | null>(null); const [message, setMessage] = useState(""); const [query, setQuery] = useState("");
  const load = async () => { const response = await fetch("/api/catalogue"); if (response.ok) setItems(await response.json()); else setMessage("Could not load inventory."); };
  useEffect(() => { void load(); }, []);
  const update = (field: keyof Form, value: string) => setForm((old) => ({ ...old, [field]: value }));
  const reset = () => { setEditing(null); setForm(empty); setMessage(""); };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const body = { category: form.category, item: form.item, brand: form.brand || undefined, model: form.model || undefined, unit: form.unit, unitPricePaise: Math.round(Number(form.unitPrice) * 100) }; const response = await fetch(editing ? `/api/catalogue/${editing.id}` : "/api/catalogue", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) { setMessage(data.error?.fieldErrors?.category?.[0] ?? data.error?.fieldErrors?.item?.[0] ?? data.error ?? "Could not save inventory item."); return; } reset(); setMessage(editing ? "Inventory item updated." : "Inventory item added."); await load(); }
  function edit(item: Item) { setEditing(item); setForm({ category: item.category.name, item: item.name, brand: item.manufacturer ?? "", model: item.model ?? "", unitPrice: String(item.clientRatePaise / 100), unit: item.unit }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function remove(item: Item) { if (!window.confirm(`Delete ${item.name}? Historical quote snapshots remain unchanged.`)) return; const response = await fetch(`/api/catalogue/${item.id}`, { method: "DELETE" }); if (!response.ok) { setMessage("Could not delete inventory item."); return; } setMessage("Inventory item deleted."); await load(); }
  const shown = items.filter((item) => `${item.category.name} ${item.name} ${item.manufacturer ?? ""} ${item.model ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="app"><AppSidebar /><section className="content"><header><div><small>ADMIN INVENTORY</small><h1>Rate catalogue</h1><p>Add and maintain the equipment and service rates used in quotations.</p></div></header>{message && <p className="notice">{message}</p>}<section className={styles.editor}><div className={styles.editorTitle}><div><small>{editing ? "EDIT ITEM" : "NEW ITEM"}</small><h2>{editing ? editing.name : "Add inventory item"}</h2></div>{editing && <button className={styles.cancel} onClick={reset}>Cancel edit</button>}</div><form onSubmit={submit}><label>Category <input value={form.category} onChange={(e) => update("category", e.target.value)} placeholder="Audio" required /></label><label>Item <input value={form.item} onChange={(e) => update("item", e.target.value)} placeholder="Speaker" required /></label><label>Brand <input value={form.brand} onChange={(e) => update("brand", e.target.value)} placeholder="d&b audiotechnik" /></label><label>Model <input value={form.model} onChange={(e) => update("model", e.target.value)} placeholder="KSL8" /></label><label>Unit price (₹) <input type="number" min="0" step="0.01" value={form.unitPrice} onChange={(e) => update("unitPrice", e.target.value)} placeholder="8000" required /></label><label>Unit <select value={form.unit} onChange={(e) => update("unit", e.target.value)}><option>Per Day</option><option>Per Unit</option><option>Per Hour</option><option>Fixed</option></select></label><button className="primary" type="submit">{editing ? "Update item" : "Add item"}</button></form></section><section className={styles.list}><div className={styles.listHeader}><div><small>LIVE CATALOGUE</small><h2>Inventory items</h2></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search inventory" /></div><div className={styles.table}><div className={styles.head}><span>Category</span><span>Item</span><span>Brand / model</span><span>Unit price</span><span /></div>{shown.map((item) => <div className={styles.row} key={item.id}><span><b>{item.category.name}</b></span><span><b>{item.name}</b><small>{item.code}</small></span><span>{item.manufacturer || "—"}<small>{item.model || "—"}</small></span><span><b>{price.format(item.clientRatePaise / 100)}</b><small>{item.unit}</small></span><span className={styles.actions}><button onClick={() => edit(item)}>Edit</button><button onClick={() => remove(item)} className={styles.delete}>Delete</button></span></div>)}{shown.length === 0 && <p className={styles.empty}>No inventory items found.</p>}</div></section></section></main>;
}
